# Welcome to yourown-bootstrap4!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically.

# Site settings
title: bookexample
email: davbohr@gmail.com
description: > # this means to ignore newlines until "github_username:"
  
github_username: david

# Build settings
markdown: kramdown

zee_crisp_im: 764a3611-efa5-4f82-b1b0-b3de1c704019

# Exclude nodes artifacts from build
exclude:
  - package.json
  - node_modules
  - gulpfile.js
